FROM rust as build
RUN apt-get update && apt-get -y upgrade
RUN apt-get install libssl-dev
RUN apt-get -y install pkg-config musl musl-dev musl-tools
RUN rustup target add x86_64-unknown-linux-musl

COPY . /app
WORKDIR /app
RUN cargo build --target x86_64-unknown-linux-musl --release --bin iter5
CMD ["./target/x86_64-unknown-linux-musl/release/iter5"]
