version: '3'
services:
  db:
    container_name: tutor-postgres
    restart: always
    image: postgres:latest
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ezytutors
    volumes:
      - tutor-data:/var/lib/postgresql/data
      - ./c12-data/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./c12-data/init-tables.sql:/docker-entrypoint-initdb.d/init-tables.sql
    ports: 
      - 5432:5432
    networks:
      - tutor-network
volumes:
  tutor-data:
networks:
  tutor-network:
